### ISSUE TITLE
check-bugs should check for closed bugs with open gerrit patches

### ISSUE THREAD

**Issue by joejulian** [gluster/release-tools#3]
The ipv6 bug was closed during a mass close, but it was still under active development and several patches are being reviewed. I suspect that a bug should not be closed as long as a patch submission is open, and should not be closed unless patches have been accepted and applied, or all patches have been abandoned (and then I suspect the bug should only be declared as wont-fix to be closed).

**Comment by atinmu** [comment]
Thanks @joejulian for raising it. This is exactly what I was asking @anoopcs today.

**Comment by anoopcs9** [comment]
I have a sample patch for glusterfs-patch-acceptance-tests repo to address this issue. I will send it as a PR and you guys can review the change.

BTW @atinmu , my username is anoopcs9.

**Comment by atinmu** [comment]
@anoopcs9 : apologies

**Comment by nixpanic** [comment]
@anoopcs9 when you send the pull request, mark it so that it closes this issue automatically upon merge. See [this help article](https://help.github.com/articles/closing-issues-via-commit-messages/) for details.

**Comment by anoopcs9** [comment]
@nixpanic Ok.
